[package]
name = "archway-proto"
version = "0.1.0"
edition = "2021"
description = "Rust build of Archway's ProtoBuf definitions"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

categories = [
  "cryptography",
  "cryptography::cryptocurrencies",
  "database",
  "wasm",
]
keywords = ["archway", "blockchain", "cosmwasm", "proto", "smart-contracts"]

[dependencies]
prost = "0.12.4"
prost-types = "0.12.4"
tonic = { version = "0.11.0", optional = true, default-features = false, features = [
  "codegen",
  "prost",
] }
tendermint-proto = { version = "0.36.0", default-features = false }
serde = { workspace = true, optional = true }

[dev-dependencies]
anyhow = "1.0.75"
tonic = { version = "0.11.0", features = [
  "tls",
  "tls-roots",
  "tls-roots-common",
  "gzip",
] }
tokio = { version = "1.33.0", features = ["full"] }

[features]
default = ["grpc-transport", "serde"]
grpc-transport = ["grpc", "tonic/transport"]
grpc = ["tonic", "tendermint-proto/grpc"]
cosmwasm = ["serde"]
serde = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "grpc-client"
