[package]
name = "archway-proto"
version = "0.2.0"
edition = "2021"
description = "Rust build of Archway's ProtoBuf definitions"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

categories = [
  "cryptography",
  "cryptography::cryptocurrencies",
  "database",
  "wasm",
]
keywords = ["archway", "blockchain", "cosmwasm", "proto", "smart-contracts"]

[dependencies]
serde = "1.0"
prost = "0.13.3"
pbjson = "0.7.0"
pbjson-types = "0.7.0"
prost-types = "0.13.3"
tonic = { version = "0.12.3", optional = true, default-features = false, features = [
  "codegen",
  "prost",
] }
cosmos-sdk-proto = { version = "0.26.0", default-features = false, features = [
  "serde",
] }
ibc-proto = { version = "0.51.0", default-features = false, features = [
  "serde",
] }

[dev-dependencies]
serde_test = "1.0"
anyhow = "1.0.91"
tonic = { version = "0.12.3", features = ["tls", "tls-roots", "gzip"] }
tokio = { version = "1.41.0", features = ["full"] }

[features]
default = ["grpc-transport"]
std = ["prost/std", "cosmos-sdk-proto/std", "ibc-proto/std"]
grpc = ["std", "tonic", "cosmos-sdk-proto/grpc", "ibc-proto/client"]
grpc-transport = [
  "grpc",
  "tonic/transport",
  "cosmos-sdk-proto/grpc-transport",
  "ibc-proto/transport",
]
proto-descriptor = ["ibc-proto/proto-descriptor"]
# Replaces all structs that use Any with a generic type
abstract-any = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "grpc-client"
